from enum import Enum

SPLIT_BACKPROP = False
GLOBAL_TIME = 0
CHUNK_NUM = 2
DEVICE_NUM = 3
STAGE_NUM = DEVICE_NUM * CHUNK_NUM + 0
MICRO_BATCH_NUM = DEVICE_NUM * 1 + 0
MODEL_LAYER_NUM = STAGE_NUM

MAX_ACTIVATION_COUNTS = 5
OFFLOAD_TIME = 4

FPW_TIME = 24
FPW_IGW_RATE = 1.25
FPW_PGW_RATE = 0.75 
IGW_TIME = FPW_TIME * FPW_IGW_RATE
PGW_TIME = FPW_TIME * FPW_PGW_RATE
IGW_TIME = 32
PGW_TIME = 16
COMM_TIME = 1


def UPDATE_TIME():
    global GLOBAL_TIME
    GLOBAL_TIME+=1

def DECREASE_TIME():
    global GLOBAL_TIME
    GLOBAL_TIME-=1

def GET_TIME():
    global GLOBAL_TIME
    return GLOBAL_TIME

class WorkloadType(Enum):
    FORWARD_PASS_WORKLOAD = "F"
    INPUT_GRADIENT_WORKLOAD = "B"
    PARAMETER_GRADIENT_WORKLOAD = "W"


class StageSearchOrder(Enum):
    Random = "Random"
    IncDec = "IncDec"

class RunMode(Enum):
    SEARCH_SCHEDULE = "search_schedule"
    Z3_SOLVE = "z3"
    GUROBI_SOLVE = "gurobi"

RUN_MODE = RunMode.GUROBI_SOLVE
SOLVING_TIME_LIMIT = 30
STAGE_SEARCH_METHOD = StageSearchOrder.Random