from enum import Enum
GLOBAL_TIME = 0

DEVICE_NUM = 4
STAGE_NUM = DEVICE_NUM * 2 + 0
MICRO_BATCH_NUM = DEVICE_NUM * 4 + 0
MODEL_LAYER_NUM = STAGE_NUM

FPW_TIME = 5
FPW_IGW_RATE = 1.80
FPW_PGW_RATE = 0.80 
IGW_TIME = FPW_TIME * FPW_IGW_RATE
PGW_TIME = FPW_TIME * FPW_PGW_RATE
COMM_TIME = 1

def UPDATE_TIME():
    global GLOBAL_TIME
    GLOBAL_TIME+=1

def DECREASE_TIME():
    global GLOBAL_TIME
    GLOBAL_TIME-=1

def GET_TIME():
    global GLOBAL_TIME
    return GLOBAL_TIME

class WorkloadType(Enum):
    FORWARD_PASS_WORKLOAD = "F"
    INPUT_GRADIENT_WORKLOAD = "B"
    PARAMETER_GRADIENT_WORKLOAD = "W"