from enum import Enum
GLOBAL_TIME = 0

DEVICE_NUM = 4
STAGE_NUM = DEVICE_NUM * 2 + 0
MICRO_BATCH_NUM = DEVICE_NUM * 2 + 0
MODEL_LAYER_NUM = STAGE_NUM

FPW_TIME = 20
FPW_IGW_RATE = 1.80
FPW_PGW_RATE = 0.60 
IGW_TIME = FPW_TIME * FPW_IGW_RATE
PGW_TIME = FPW_TIME * FPW_PGW_RATE
COMM_TIME = 1

class WorkloadType(Enum):
    FORWARD_PASS_WORKLOAD = "ForwardPassWorkload"
    INPUT_GRADIENT_WORKLOAD = "InputGradientWorkload"
    PARAMETER_GRADIENT_WORKLOAD = "ParameterGradientWorkload"